name: "Pnpm prepare (Node, Pnpm install)"
description: "Install right node version and node dependencies"
inputs:
  github-token:
    description: "GitHub token for private registry access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
        scope: "@yurasytnyk"

    - name: Configure Environment
      run: |
        echo "NODE_AUTH_TOKEN=${{ inputs.github-token }}" >> $GITHUB_ENV
        # Debugging: Print the length of the token to verify it exists
        TOKEN_LENGTH=${#NODE_AUTH_TOKEN}
        echo "Debug: NODE_AUTH_TOKEN is set. Length: $TOKEN_LENGTH"

        # Debugging: Print the first 4 characters
        echo "Debug: Token prefix: ${NODE_AUTH_TOKEN:0:4}..."
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
