name: "Pnpm prepare (Node, Pnpm install)"
description: "Install right node version and node dependencies"
inputs:
  github-token:
    description: "GitHub token for private registry access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm
        registry-url: "https://registry.npmjs.org"
        scope: "@yura_sytnyk"
        always-auth: true
        token: ${{ inputs.github-token }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
