name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/pnpm-prepare
        with:
          github-token: ${{ secrets.NPM_GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to GitHub Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore: update versions"
          title: "chore: update versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
